name: Build & Upload Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t titanic-packaging:latest .

      - name: Save image to tarball
        run: docker save titanic-packaging:latest -o titanic-packaging.tar

      - name: Upload container tarball
        uses: actions/upload-artifact@v3
        with:
          name: titanic-packaging-container
          path: titanic-packaging.tar
